using System.Collections.Generic;

namespace UltimateTeam.Toolkit.Parameter
{
    public class Team : SearchParameterBase<uint>
    {
        public const uint FcKaiserslautern = 29;
		public const uint FcKoln = 31;
		public const uint FcNurnberg = 171;
		public const uint FcUnionBerlin = 1831;
		public const uint FsvMainz05 = 169;
		public const uint Hoffenheim = 10029;
		public const uint AVladikavkaz = 110230;
		public const uint AaB = 820;
		public const uint AalesundsFk = 1755;
		public const uint Aberdeen = 77;
		public const uint AcAjaccio = 614;
		public const uint AcArlesAvignon = 111989;
		public const uint AcHorsens = 1446;
		public const uint AcademicaCoimbra = 1901;
		public const uint AccringtonStanley = 110313;
		public const uint AdAlcorcon = 100831;
		public const uint AdelaideUnited = 111393;
		public const uint AdmiraWackerModling = 111821;
		public const uint AdoDenHaag = 650;
		public const uint AekAthens = 278;
		public const uint AfcWimbledon = 112259;
		public const uint AgfAarhus = 271;
		public const uint Aik = 433;
		public const uint AjAuxerre = 57;
		public const uint Ajax = 245;
		public const uint AlWehdah = 112408;
		public const uint AlAhli = 112387;
		public const uint AldershotTown = 382;
		public const uint AlemanniaAachen = 1826;
		public const uint AlEttifaq = 112096;
		public const uint AlFaisaly = 112389;
		public const uint AlFateh = 112390;
		public const uint AlHilal = 605;
		public const uint AlIttihad = 607;
		public const uint AlNassr = 112139;
		public const uint AlRaed = 112392;
		public const uint AlShabab = 111674;
		public const uint Alshoulla = 112407;
		public const uint AlTaawoun = 112393;
		public const uint America = 1879;
		public const uint AmericaMineiro = 112001;
		public const uint AmiensSc = 1816;
		public const uint AmkarPerm = 110234;
		public const uint Anderlecht = 229;
		public const uint AngersSco = 1530;
		public const uint AnzhiMakhachkala = 100766;
		public const uint Arsenal = 1;
		public const uint AsMonaco = 69;
		public const uint AsNancy = 1823;
		public const uint AsSaintEtienne = 1819;
		public const uint Ascoli = 1846;
		public const uint AssociaoAcadmicadeCoimbra = 1901;
		public const uint AstonVilla = 2;
		public const uint Atalanta = 39;
		public const uint AthleticClubdeBilbao = 448;
		public const uint Atlante = 101116;
		public const uint Atlas = 101114;
		public const uint AtleticodeMadrid = 240;
		public const uint AtleticoGoianiense = 112119;
		public const uint AtleticoMineiro = 1035;
		public const uint AtleticoParanaense = 1039;
		public const uint AtvidabergsFf = 111835;
		public const uint AustriaWien = 256;
		public const uint Avai = 111976;
		public const uint Az = 1906;
		public const uint Bahia = 1598;
		public const uint Bari = 1848;
		public const uint Barnet = 135;
		public const uint Barnsley = 1932;
		public const uint Bayer04Leverkusen = 32;
		public const uint BayernMunchen = 21;
		public const uint BeiraMar = 1897;
		public const uint Benfica = 234;
		public const uint BirminghamCity = 88;
		public const uint BkHacken = 711;
		public const uint BlackburnRovers = 3;
		public const uint Blackpool = 1926;
		public const uint BohemianFc = 305;
		public const uint Bologna = 189;
		public const uint BoltonWanderers = 4;
		public const uint BorussiaDortmund = 22;
		public const uint BorussiaMgladbach = 23;
		public const uint Botafogo = 517;
		public const uint Bournemouth = 1943;
		public const uint BradfordCity = 1804;
		public const uint Braga = 1896;
		public const uint BrayWanderers = 838;
		public const uint Brentford = 1925;
		public const uint Brescia = 190;
		public const uint BrightonHoveAlbion = 1808;
		public const uint BrisbaneRoar = 111395;
		public const uint BristolCity = 1919;
		public const uint BristolRovers = 1962;
		public const uint Brondby = 269;
		public const uint BscYoungBoys = 900;
		public const uint Burnley = 1796;
		public const uint BurtonAlbion = 15015;
		public const uint Bury = 1945;
		public const uint BusanIPark = 1476;
		public const uint CaOsasuna = 479;
		public const uint Cagliari = 1842;
		public const uint CardiffCity = 1961;
		public const uint CarlisleUnited = 1480;
		public const uint Catania = 110364;
		public const uint CdAlcoyano = 110833;
		public const uint CdFeirense = 10019;
		public const uint CdGuadalajaraSpain = 111827;
		public const uint CdLugo = 110831;
		public const uint CdMirandes = 110069;
		public const uint CdNacional = 1891;
		public const uint CdNacionaldeMadeira = 1891;
		public const uint CdNumancia = 477;
		public const uint CeSabadell = 15021;
		public const uint Ceara = 111059;
		public const uint Celtic = 78;
		public const uint CentralCoastMariners = 111396;
		public const uint CercleBrugge = 1750;
		public const uint Cesena = 110915;
		public const uint ChamNiortais = 1813;
		public const uint Charleroi = 670;
		public const uint CharltonAthletic = 89;
		public const uint Chelsea = 5;
		public const uint CheltenhamTown = 1936;
		public const uint Chesterfield = 1924;
		public const uint ChicagoFire = 693;
		public const uint ChievoVerona = 192;
		public const uint ChivasUsa = 111070;
		public const uint ChunnamDragons = 1475;
		public const uint Cittadella = 111993;
		public const uint ClermontFoot = 1815;
		public const uint ClubBrugge = 231;
		public const uint ClubLeon = 110781;
		public const uint ColchesterUnited = 1935;
		public const uint ColoradoRapids = 694;
		public const uint ColumbusCrew = 687;
		public const uint CordobaCf = 1867;
		public const uint Corinthians = 1041;
		public const uint Coritiba = 111044;
		public const uint CorkCity = 422;
		public const uint CoventryCity = 1800;
		public const uint CracoviaKrakow = 110747;
		public const uint CrawleyTown = 110890;
		public const uint CreweAlexandra = 121;
		public const uint Crotone = 110734;
		public const uint CruzAzul = 1878;
		public const uint Cruzeiro = 568;
		public const uint CrystalPalace = 1799;
		public const uint CsMaritimo = 1893;
		public const uint CsSedan = 613;
		public const uint CskaMoskva = 315;
		public const uint DcUnited = 688;
		public const uint DaeguFc = 2056;
		public const uint DaejeonCitizen = 980;
		public const uint DagenhamRedbridge = 373;
		public const uint DeGraafschap = 635;
		public const uint DerbyCounty = 91;
		public const uint DerryCity = 445;
		public const uint DijonFootball = 110569;
		public const uint DinamoMoskva = 312;
		public const uint DjurgardensIf = 710;
		public const uint DoncasterRovers = 142;
		public const uint DroghedaUnited = 1572;
		public const uint DundalkFc = 837;
		public const uint DundeeFc = 180;
		public const uint DundeeUnited = 181;
		public const uint DynamoDresden = 503;
		public const uint EintrachtBraunschweig = 110500;
		public const uint EintrachtFrankfurt = 1824;
		public const uint ElcheCf = 468;
		public const uint Empoli = 1746;
		public const uint EnAvantGuingamp = 62;
		public const uint EnergieCottbus = 162;
		public const uint ErzgebirgeAue = 506;
		public const uint EsTroyes = 294;
		public const uint Esbjerg = 1445;
		public const uint Estoril = 10020;
		public const uint EstorilPraia = 10020;
		public const uint EstudiantesTecos = 110780;
		public const uint Everton = 7;
		public const uint EvianThononGaillardFc = 111271;
		public const uint Excelsior = 1971;
		public const uint ExeterCity = 143;
		public const uint FcPaosdeFerreira = 182;
		public const uint FcAugsburg = 100409;
		public const uint FcBarcelona = 241;
		public const uint FcBarcelonaB = 110704;
		public const uint FcBasel = 896;
		public const uint FcCartagena = 100851;
		public const uint FcCopenhagen = 819;
		public const uint FcDallas = 695;
		public const uint FcGroningen = 1915;
		public const uint FcIngolstadt04 = 111239;
		public const uint FcIstres = 1820;
		public const uint FcKrasnodar = 112218;
		public const uint FcLausanneSports = 1862;
		public const uint FcLorient = 217;
		public const uint FcLuzern = 897;
		public const uint FcMetz = 68;
		public const uint FcMidtjylland = 1516;
		public const uint FcNantes = 71;
		public const uint FcNordsjlland = 1788;
		public const uint FcPorto = 236;
		public const uint FcRostov = 110231;
		public const uint FcSchalke04 = 34;
		public const uint FcSeoul = 982;
		public const uint FcSion = 110770;
		public const uint FcSochaux = 226;
		public const uint FcStGallen = 898;
		public const uint FcStPauli = 110329;
		public const uint FcThun = 1715;
		public const uint FcTwente = 1908;
		public const uint FcUtrecht = 1903;
		public const uint FcVolgaNizhniyNovgorod = 112217;
		public const uint FcZurich = 894;
		public const uint Feyenoord = 246;
		public const uint Figueirense = 111045;
		public const uint Fiorentina = 110374;
		public const uint FkHaugesund = 1463;
		public const uint Flamengo = 1043;
		public const uint FleetwoodTown = 112260;
		public const uint Fluminense = 567;
		public const uint FortunaDsseldorf = 110636;
		public const uint FredrikstadFk = 2041;
		public const uint FsvFrankfurt = 110596;
		public const uint Fulham = 144;
		public const uint Gais = 111594;
		public const uint GalatasaraySk = 325;
		public const uint GalwayUnited = 1571;
		public const uint GangwonFc = 112115;
		public const uint GazelecAjaccio = 110316;
		public const uint GefleIf = 111277;
		public const uint Genk = 673;
		public const uint Genoa = 110556;
		public const uint Gent = 674;
		public const uint GetafeCf = 1860;
		public const uint GifSundsvall = 1596;
		public const uint GilVicente = 1888;
		public const uint GilVicenteFc = 1888;
		public const uint Gillingham = 1802;
		public const uint GironaFc = 110062;
		public const uint GirondinsBordeaux = 59;
		public const uint GksBelchatow = 110744;
		public const uint Gliwice = 111086;
		public const uint GoldCoastUnited = 112078;
		public const uint GornikZabrze = 420;
		public const uint GranadaCf = 110832;
		public const uint GrasshopperClub = 322;
		public const uint Gremio = 1629;
		public const uint Grosseto = 111491;
		public const uint Guadalajara = 1880;
		public const uint Guimaraes = 1887;
		public const uint GwangJuFc = 112258;
		public const uint GyeongNamFc = 111588;
		public const uint Hajer = 112394;
		public const uint HalmstadsBk = 321;
		public const uint HamburgerSv = 28;
		public const uint Hannover96 = 485;
		public const uint HansaRostock = 27;
		public const uint HartlepoolUnited = 1941;
		public const uint HeartofMidlothian = 80;
		public const uint HelsingborgsIf = 432;
		public const uint HeraclesAlmelo = 100634;
		public const uint HerculesCf = 100879;
		public const uint HerefordUnited = 147;
		public const uint HerthaBsc = 166;
		public const uint Hibernian = 81;
		public const uint HonefossBk = 1841;
		public const uint HoustonDynamo = 698;
		public const uint HuddersfieldTown = 1939;
		public const uint HullCity = 1952;
		public const uint IfElfsborg = 700;
		public const uint IfkGoteborg = 319;
		public const uint IfkNorrkoping = 702;
		public const uint IkStart = 1524;
		public const uint IncheonUnitedFc = 110765;
		public const uint Inter = 44;
		public const uint Internacional = 1048;
		public const uint InvernessCaledonianThistle = 620;
		public const uint IpswichTown = 94;
		public const uint JagielloniaBialystok = 110745;
		public const uint JaguaresdeChiapas = 110151;
		public const uint JejuUnitedFc = 1478;
		public const uint JeonbukHyundaiMotors = 1477;
		public const uint JuveStabia = 112124;
		public const uint Juventus = 45;
		public const uint KaizerChiefs = 110929;
		public const uint KalmarFf = 1439;
		public const uint KapfenbergerSv = 15011;
		public const uint KarlsruherSc = 1832;
		public const uint Kilmarnock = 82;
		public const uint KoronaKielce = 111083;
		public const uint Kortrijk = 100081;
		public const uint KrylyaSovetovSamara = 100764;
		public const uint KubanKrasnodar = 110089;
		public const uint LaSpezia = 110741;
		public const uint Lanciano = 112020;
		public const uint Lazio = 46;
		public const uint LbChateauroux = 212;
		public const uint LeHavreAc = 1738;
		public const uint LeMansFc = 1739;
		public const uint Lecce = 347;
		public const uint LechPoznan = 873;
		public const uint LechiaGdansk = 111091;
		public const uint LeedsUnited = 8;
		public const uint LegiaWarszawa = 1871;
		public const uint LeicesterCity = 95;
		public const uint LevanteUd = 1853;
		public const uint LeytonOrient = 1958;
		public const uint Lierse = 239;
		public const uint LillestromSk = 299;
		public const uint Liverpool = 9;
		public const uint Livorno = 1844;
		public const uint LksLodz = 111085;
		public const uint Lokeren = 2007;
		public const uint LokomotivMoskva = 100765;
		public const uint LosAngelesGalaxy = 697;
		public const uint LoscLille = 65;
		public const uint MacclesfieldTown = 1959;
		public const uint MalagaCf = 573;
		public const uint MalmoFf = 320;
		public const uint ManchesterCity = 10;
		public const uint ManchesterUnited = 11;
		public const uint Maritimo = 1893;
		public const uint Mechelen = 110724;
		public const uint MelbourneHeart = 112224;
		public const uint MelbourneVictory = 111397;
		public const uint Middlesbrough = 12;
		public const uint Milan = 47;
		public const uint Millwall = 97;
		public const uint MiltonKeynesDons = 1798;
		public const uint MjallbyAif = 112072;
		public const uint Modena = 1744;
		public const uint MoldeFk = 417;
		public const uint MonarcasMorelia = 1028;
		public const uint Monterrey = 1032;
		public const uint MontpellierSc = 70;
		public const uint MontrealImpact = 111139;
		public const uint MordovSaransk = 110106;
		public const uint Morecambe = 357;
		public const uint MoreiraConegos = 1900;
		public const uint Moreirense = 1900;
		public const uint Motherwell = 83;
		public const uint MsvDuisburg = 1825;
		public const uint NRecife = 111050;
		public const uint NacBreda = 1904;
		public const uint Najran = 112395;
		public const uint Napoli = 48;
		public const uint NasticdeTarragona = 15019;
		public const uint Nec = 1910;
		public const uint NeuchatelXamax = 435;
		public const uint NewEnglandRevolution = 691;
		public const uint NewYorkRedBulls = 689;
		public const uint NewcastleUnited = 13;
		public const uint NewcastleUnitedJets = 111398;
		public const uint NimesOlympique = 224;
		public const uint NorthamptonTown = 1930;
		public const uint NorwichCity = 1792;
		public const uint NottinghamForest = 14;
		public const uint NottsCounty = 1937;
		public const uint Novara = 112225;
		public const uint OddGrenland = 1456;
		public const uint OdenseBk = 272;
		public const uint OgcNice = 72;
		public const uint OldhamAthletic = 1920;
		public const uint Olhanense = 111540;
		public const uint Olympiakos = 280;
		public const uint OlympiquedeMarseille = 219;
		public const uint OlympiqueLyonnais = 66;
		public const uint OrebroSk = 705;
		public const uint OrlandoPirates = 110930;
		public const uint OudHeverleeLeuven = 100087;
		public const uint OxfordUnited = 1951;
		public const uint PCampinas = 111043;
		public const uint Pachuca = 110147;
		public const uint PacosdeFerreira = 1892;
		public const uint Padova = 110912;
		public const uint Palermo = 1843;
		public const uint Palmeiras = 383;
		public const uint Panathinaikos = 1884;
		public const uint Paok = 393;
		public const uint ParisSaintGermain = 73;
		public const uint Parma = 50;
		public const uint PecZwolle = 1914;
		public const uint PerthGlory = 111399;
		public const uint Pescara = 200;
		public const uint PeterboroughUnited = 1938;
		public const uint PhiladelphiaUnion = 112134;
		public const uint PlymouthArgyle = 1929;
		public const uint PodbeskidzieBielskoBiala = 111087;
		public const uint PohangSteelers = 1474;
		public const uint PoloniaWarszawa = 1570;
		public const uint PortVale = 1928;
		public const uint PortlandTimbers = 111140;
		public const uint Portsmouth = 1790;
		public const uint Portuguesa = 111292;
		public const uint PrestonNorthEnd = 1801;
		public const uint Psv = 247;
		public const uint Puebla = 110152;
		public const uint QueensParkRangers = 15;
		public const uint Queretaro = 110150;
		public const uint RacingClubdeLens = 64;
		public const uint RacingdeSantander = 456;
		public const uint RandersFc = 1786;
		public const uint RapidWien = 254;
		public const uint RayoVallecano = 480;
		public const uint RcCeltadeVigo = 450;
		public const uint RcDeportivo = 242;
		public const uint RcRecreativo = 571;
		public const uint RcdEspanyol = 452;
		public const uint RcdMallorca = 453;
		public const uint Reading = 1793;
		public const uint RealBetisBalompie = 449;
		public const uint RealMadrid = 243;
		public const uint RealMurciaCf = 1855;
		public const uint RealSaltLake = 111065;
		public const uint RealSociedad = 457;
		public const uint RealSportingdeGijon = 459;
		public const uint RealValladolid = 462;
		public const uint RealZaragoza = 244;
		public const uint RedBullSalzburg = 191;
		public const uint Reggina = 203;
		public const uint RioAve = 744;
		public const uint RioAveFc = 744;
		public const uint RkcWaalwijk = 1905;
		public const uint RmCastilla = 110710;
		public const uint Rochdale = 1955;
		public const uint RodaJcKerkrade = 1902;
		public const uint Roma = 52;
		public const uint RosenborgBk = 298;
		public const uint RossCounty = 631;
		public const uint RotherhamUnited = 1797;
		public const uint RubinKazan = 110227;
		public const uint RuchChorzow = 874;
		public const uint SRecife = 111057;
		public const uint Sampdoria = 1837;
		public const uint SanJoseEarthquakes = 111928;
		public const uint SanLuis = 110149;
		public const uint SandnesUlf = 112374;
		public const uint SangjuSangmuPhoenixFc = 2055;
		public const uint Santos = 1053;
		public const uint SantosLaguna = 110144;
		public const uint SaoPaulo = 598;
		public const uint Sassuolo = 111974;
		public const uint ScBastia = 58;
		public const uint ScBeiraMar = 1897;
		public const uint ScBraga = 1896;
		public const uint ScFreiburg = 25;
		public const uint ScHeerenveen = 1913;
		public const uint ScOlhanense = 111540;
		public const uint ScPaderborn = 10030;
		public const uint ScWienerNeustadt = 111373;
		public const uint ScunthorpeUnited = 1949;
		public const uint SdHuesca = 110839;
		public const uint SdPonferradina = 2023;
		public const uint SeattleSounders = 111144;
		public const uint SeongnamIlhwaChunma = 981;
		public const uint ServetteFc = 324;
		public const uint SevillaFc = 481;
		public const uint ShamrockRovers = 306;
		public const uint SheffieldUnited = 1794;
		public const uint SheffieldWednesday = 1807;
		public const uint Shelbourne = 834;
		public const uint ShrewsburyTown = 127;
		public const uint Siena = 1838;
		public const uint SilkeborgIf = 270;
		public const uint SkBrann = 919;
		public const uint SlBenfica = 234;
		public const uint SlaskWroclaw = 111092;
		public const uint SligoRovers = 563;
		public const uint SmCaen = 210;
		public const uint Snderjyske = 1447;
		public const uint SogndalFotball = 1465;
		public const uint Southampton = 17;
		public const uint SouthendUnited = 1954;
		public const uint SpartakMoskva = 100767;
		public const uint SpartakNalchik = 110103;
		public const uint SportingCp = 237;
		public const uint SportingKc = 696;
		public const uint SportingLisbon = 237;
		public const uint SpvggGreutherFrth = 165;
		public const uint SsvJahn = 543;
		public const uint StJohnstone = 100804;
		public const uint StMirren = 100805;
		public const uint StPatricksAthletic = 423;
		public const uint StabaekFotball = 917;
		public const uint StadeBrestois = 378;
		public const uint StadedeReims = 379;
		public const uint StadeLavallois = 1814;
		public const uint StadeRennais = 74;
		public const uint Standard = 232;
		public const uint Stevenage = 361;
		public const uint StokeCity = 1806;
		public const uint StromsgodsetToppfotball = 922;
		public const uint SturmGraz = 209;
		public const uint Sunderland = 106;
		public const uint SuwonSamsungBluewings = 983;
		public const uint SvMattersburg = 1785;
		public const uint SvRied = 780;
		public const uint SvSandhausen = 110178;
		public const uint SwanseaCity = 1960;
		public const uint SwindonTown = 1934;
		public const uint SydneyFc = 111400;
		public const uint SyrianskaFc = 112267;
		public const uint Szczecin = 110746;
		public const uint TerekGrozny = 110109;
		public const uint Terni = 570;
		public const uint TigresUanl = 1970;
		public const uint Toluca = 1882;
		public const uint TomTomsk = 110233;
		public const uint Torino = 54;
		public const uint TorontoFc = 111651;
		public const uint TorquayUnited = 1946;
		public const uint TottenhamHotspur = 18;
		public const uint ToulouseFc = 1809;
		public const uint ToursFc = 110326;
		public const uint TranmereRovers = 15048;
		public const uint TromsoIl = 418;
		public const uint Tsv1860Munchen = 33;
		public const uint Ucd = 111132;
		public const uint Unam = 1881;
		public const uint UdAlmeria = 1861;
		public const uint UdLasPalmas = 472;
		public const uint Udinese = 55;
		public const uint UlsanHyundaiFc = 1473;
		public const uint UniaoDesportivadeLeiria = 1895;
		public const uint UsBoulogne = 111376;
		public const uint ValenciaCf = 461;
		public const uint ValenciennesFc = 110456;
		public const uint ValerengaFotball = 920;
		public const uint VancouverWhitecaps = 101112;
		public const uint Varese = 112237;
		public const uint VascodaGama = 569;
		public const uint Vercelli = 112398;
		public const uint Verona = 206;
		public const uint VfBStuttgart = 36;
		public const uint VfLBochum = 160;
		public const uint VfLWolfsburg = 175;
		public const uint VfRAalen = 550;
		public const uint Vicenza = 1847;
		public const uint VikingFk = 300;
		public const uint VillarrealB = 110902;
		public const uint VillarrealCf = 483;
		public const uint Vitesse = 1909;
		public const uint VitoriaGuimaraes = 1887;
		public const uint VitoriaSetubal = 665;
		public const uint VvvVenlo = 100651;
		public const uint WaaslandBeveren = 110913;
		public const uint WackerInnsbruck = 2045;
		public const uint Walsall = 1803;
		public const uint WanderersFc = 112427;
		public const uint Waregem = 15005;
		public const uint Watford = 1795;
		public const uint WellingtonPhoenix = 111766;
		public const uint WerderBremen = 38;
		public const uint WestBromwichAlbion = 109;
		public const uint WestHamUnited = 19;
		public const uint WidzewLodz = 301;
		public const uint WiganAthletic = 1917;
		public const uint WillemIi = 1907;
		public const uint WislaKrakow = 1873;
		public const uint WolfsbergerAc = 111822;
		public const uint WolverhamptonWanderers = 110;
		public const uint WycombeWanderers = 1933;
		public const uint XerezCd = 1742;
		public const uint XoloitzcuintlesdeTijuana = 111678;
		public const uint YeovilTown = 346;
		public const uint YorkCity = 1948;
		public const uint ZaglebieLubin = 110749;
		public const uint ZenitStPetersburg = 100769;

    private Team(string description, uint value)
    {
        Description = description;
        Value = value;
    }

    public static IEnumerable<Team> GetAll()
    {
            yield return new Team("FC Barcelona", FcBarcelona);
            yield return new Team("FC Bayern", BayernMunchen);
            yield return new Team("Manchester United", ManchesterUnited);
            yield return new Team("Real Madrid", RealMadrid);
            yield return new Team("1. FC Kaiserslautern", FcKaiserslautern);
			yield return new Team("1. FC Koln", FcKoln);
			yield return new Team("1. FC Nurnberg", FcNurnberg);
			yield return new Team("1. FC Union Berlin", FcUnionBerlin);
			yield return new Team("1. FSV Mainz 05", FsvMainz05);
			yield return new Team("1899 Hoffenheim", Hoffenheim);
			yield return new Team("A. Vladikavkaz", AVladikavkaz);
			yield return new Team("AaB", AaB);
			yield return new Team("Aalesunds FK", AalesundsFk);
			yield return new Team("Aberdeen", Aberdeen);
			yield return new Team("AC Ajaccio", AcAjaccio);
			yield return new Team("AC Arles-Avignon", AcArlesAvignon);
			yield return new Team("AC Horsens ", AcHorsens);
			yield return new Team("Academica Coimbra", AcademicaCoimbra);
			yield return new Team("Accrington Stanley", AccringtonStanley);
			yield return new Team("AD Alcorcon", AdAlcorcon);
			yield return new Team("Admira Wacker Modling", AdmiraWackerModling);
			yield return new Team("Admira Wacker Modling", AdmiraWackerModling);
			yield return new Team("ADO Den Haag", AdoDenHaag);
			yield return new Team("AEK Athens", AekAthens);
			yield return new Team("AFC Wimbledon", AfcWimbledon);
			yield return new Team("AGF Aarhus ", AgfAarhus);
			yield return new Team("AIK", Aik);
			yield return new Team("AJ Auxerre", AjAuxerre);
			yield return new Team("Ajax", Ajax);
			yield return new Team("Al Wehdah", AlWehdah);
			yield return new Team("Al-Ahli", AlAhli);
			yield return new Team("Aldershot Town", AldershotTown);
			yield return new Team("Alemannia Aachen", AlemanniaAachen);
			yield return new Team("Al-Ettifaq", AlEttifaq);
			yield return new Team("Al-Faisaly", AlFaisaly);
			yield return new Team("Al-Fateh", AlFateh);
			yield return new Team("Al-Hilal", AlHilal);
			yield return new Team("Al-Ittihad", AlIttihad);
			yield return new Team("Al-Nassr", AlNassr);
			yield return new Team("Al-Raed", AlRaed);
			yield return new Team("Al-Shabab", AlShabab);
			yield return new Team("Alshoulla", Alshoulla);
			yield return new Team("Al-Taawoun", AlTaawoun);
			yield return new Team("America", America);
			yield return new Team("America Mineiro", AmericaMineiro);
			yield return new Team("Amiens SC", AmiensSc);
			yield return new Team("Amkar Perm", AmkarPerm);
			yield return new Team("Anderlecht", Anderlecht);
			yield return new Team("Angers SCO", AngersSco);
			yield return new Team("Anzhi Makhachkala", AnzhiMakhachkala);
			yield return new Team("Arsenal", Arsenal);
			yield return new Team("AS Monaco", AsMonaco);
			yield return new Team("AS Nancy", AsNancy);
			yield return new Team("AS Saint-Etienne", AsSaintEtienne);
			yield return new Team("Ascoli", Ascoli);
			yield return new Team("Associao Acadmica de Coimbra", AssociaoAcadmicadeCoimbra);
			yield return new Team("Aston Villa", AstonVilla);
			yield return new Team("Atalanta", Atalanta);
			yield return new Team("Athletic Club de Bilbao", AthleticClubdeBilbao);
			yield return new Team("Atlante", Atlante);
			yield return new Team("Atlas", Atlas);
			yield return new Team("Atletico de Madrid", AtleticodeMadrid);
			yield return new Team("Atletico Goianiense", AtleticoGoianiense);
			yield return new Team("Atletico Mineiro", AtleticoMineiro);
			yield return new Team("Atletico Paranaense", AtleticoParanaense);
			yield return new Team("Atvidabergs FF", AtvidabergsFf);
			yield return new Team("Austria Wien", AustriaWien);
			yield return new Team("Avai", Avai);
			yield return new Team("AZ", Az);
			yield return new Team("Bahia", Bahia);
			yield return new Team("Bari", Bari);
			yield return new Team("Barnet", Barnet);
			yield return new Team("Barnsley", Barnsley);
			yield return new Team("Bayer 04 Leverkusen", Bayer04Leverkusen);
			yield return new Team("Bayern Munchen", BayernMunchen);
			yield return new Team("Beira Mar", BeiraMar);
			yield return new Team("Benfica ", Benfica);
			yield return new Team("Birmingham City", BirminghamCity);
			yield return new Team("BK Hacken", BkHacken);
			yield return new Team("Blackburn Rovers", BlackburnRovers);
			yield return new Team("Blackpool", Blackpool);
			yield return new Team("Bohemian FC", BohemianFc);
			yield return new Team("Bologna", Bologna);
			yield return new Team("Bolton Wanderers", BoltonWanderers);
			yield return new Team("Borussia Dortmund", BorussiaDortmund);
			yield return new Team("Borussia M'gladbach", BorussiaMgladbach);
			yield return new Team("Botafogo", Botafogo);
			yield return new Team("Bournemouth", Bournemouth);
			yield return new Team("Bradford City", BradfordCity);
			yield return new Team("Braga", Braga);
			yield return new Team("Bray Wanderers", BrayWanderers);
			yield return new Team("Brentford", Brentford);
			yield return new Team("Brescia", Brescia);
			yield return new Team("Brighton & Hove Albion", BrightonHoveAlbion);
			yield return new Team("Brisbane Roar", BrisbaneRoar);
			yield return new Team("Bristol City", BristolCity);
			yield return new Team("Bristol Rovers", BristolRovers);
			yield return new Team("Brondby ", Brondby);
			yield return new Team("BSC Young Boys", BscYoungBoys);
			yield return new Team("Burnley", Burnley);
			yield return new Team("Burton Albion", BurtonAlbion);
			yield return new Team("Bury", Bury);
			yield return new Team("Busan I'Park", BusanIPark);
			yield return new Team("CA Osasuna", CaOsasuna);
			yield return new Team("Cagliari", Cagliari);
			yield return new Team("Cardiff City", CardiffCity);
			yield return new Team("Carlisle United", CarlisleUnited);
			yield return new Team("Catania", Catania);
			yield return new Team("CD Alcoyano", CdAlcoyano);
			yield return new Team("CD Feirense", CdFeirense);
			yield return new Team("CD Guadalajara (Spain)", CdGuadalajaraSpain);
			yield return new Team("CD Lugo", CdLugo);
			yield return new Team("CD Mirandes", CdMirandes);
			yield return new Team("CD Nacional", CdNacional);
			yield return new Team("CD Nacional de Madeira ", CdNacionaldeMadeira);
			yield return new Team("CD Numancia", CdNumancia);
			yield return new Team("CE Sabadell", CeSabadell);
			yield return new Team("Ceara", Ceara);
			yield return new Team("Celtic", Celtic);
			yield return new Team("Central Coast Mariners", CentralCoastMariners);
			yield return new Team("Cercle Brugge", CercleBrugge);
			yield return new Team("Cesena", Cesena);
			yield return new Team("Cham. Niortais", ChamNiortais);
			yield return new Team("Charleroi", Charleroi);
			yield return new Team("Charlton Athletic", CharltonAthletic);
			yield return new Team("Chelsea", Chelsea);
			yield return new Team("Cheltenham Town", CheltenhamTown);
			yield return new Team("Chesterfield", Chesterfield);
			yield return new Team("Chicago Fire", ChicagoFire);
			yield return new Team("Chievo Verona", ChievoVerona);
			yield return new Team("Chivas USA", ChivasUsa);
			yield return new Team("Chunnam Dragons", ChunnamDragons);
			yield return new Team("Cittadella", Cittadella);
			yield return new Team("Clermont Foot", ClermontFoot);
			yield return new Team("Club Brugge", ClubBrugge);
			yield return new Team("Club Leon", ClubLeon);
			yield return new Team("Colchester United", ColchesterUnited);
			yield return new Team("Colorado Rapids", ColoradoRapids);
			yield return new Team("Columbus Crew", ColumbusCrew);
			yield return new Team("Cordoba CF", CordobaCf);
			yield return new Team("Corinthians", Corinthians);
			yield return new Team("Coritiba", Coritiba);
			yield return new Team("Cork City", CorkCity);
			yield return new Team("Coventry City", CoventryCity);
			yield return new Team("Cracovia Krakow", CracoviaKrakow);
			yield return new Team("Crawley Town", CrawleyTown);
			yield return new Team("Crewe Alexandra", CreweAlexandra);
			yield return new Team("Crotone", Crotone);
			yield return new Team("Cruz Azul", CruzAzul);
			yield return new Team("Cruzeiro", Cruzeiro);
			yield return new Team("Crystal Palace", CrystalPalace);
			yield return new Team("CS Maritimo", CsMaritimo);
			yield return new Team("CS Sedan", CsSedan);
			yield return new Team("CSKA Moskva", CskaMoskva);
			yield return new Team("D.C. United", DcUnited);
			yield return new Team("Daegu FC", DaeguFc);
			yield return new Team("Daejeon Citizen", DaejeonCitizen);
			yield return new Team("Dagenham & Redbridge", DagenhamRedbridge);
			yield return new Team("De Graafschap", DeGraafschap);
			yield return new Team("Derby County", DerbyCounty);
			yield return new Team("Derry City", DerryCity);
			yield return new Team("Dijon Football", DijonFootball);
			yield return new Team("Dinamo Moskva", DinamoMoskva);
			yield return new Team("Djurgardens IF", DjurgardensIf);
			yield return new Team("Doncaster Rovers", DoncasterRovers);
			yield return new Team("Drogheda United", DroghedaUnited);
			yield return new Team("Dundalk FC", DundalkFc);
			yield return new Team("Dundee FC", DundeeFc);
			yield return new Team("Dundee United", DundeeUnited);
			yield return new Team("Dynamo Dresden", DynamoDresden);
			yield return new Team("Eintracht Braunschweig", EintrachtBraunschweig);
			yield return new Team("Eintracht Frankfurt", EintrachtFrankfurt);
			yield return new Team("Elche CF", ElcheCf);
			yield return new Team("Empoli", Empoli);
			yield return new Team("En Avant Guingamp", EnAvantGuingamp);
			yield return new Team("Energie Cottbus", EnergieCottbus);
			yield return new Team("Erzgebirge Aue", ErzgebirgeAue);
			yield return new Team("ES Troyes", EsTroyes);
			yield return new Team("Esbjerg", Esbjerg);
			yield return new Team("Estoril", Estoril);
			yield return new Team("Estoril-Praia", EstorilPraia);
			yield return new Team("Estudiantes Tecos", EstudiantesTecos);
			yield return new Team("Everton", Everton);
			yield return new Team("Evian Thonon Gaillard FC", EvianThononGaillardFc);
			yield return new Team("Excelsior", Excelsior);
			yield return new Team("Exeter City", ExeterCity);
			yield return new Team("F.C. Paos de Ferreira", FcPaosdeFerreira);
			yield return new Team("FC Augsburg", FcAugsburg);
			yield return new Team("FC Barcelona", FcBarcelona);
			yield return new Team("FC Barcelona B", FcBarcelonaB);
			yield return new Team("FC Basel", FcBasel);
			yield return new Team("FC Cartagena", FcCartagena);
			yield return new Team("FC Copenhagen", FcCopenhagen);
			yield return new Team("FC Dallas", FcDallas);
			yield return new Team("FC Groningen", FcGroningen);
			yield return new Team("FC Ingolstadt 04", FcIngolstadt04);
			yield return new Team("FC Istres", FcIstres);
			yield return new Team("FC Krasnodar", FcKrasnodar);
			yield return new Team("FC Lausanne-Sports", FcLausanneSports);
			yield return new Team("FC Lorient", FcLorient);
			yield return new Team("FC Luzern", FcLuzern);
			yield return new Team("FC Metz", FcMetz);
			yield return new Team("FC Midtjylland ", FcMidtjylland);
			yield return new Team("FC Nantes", FcNantes);
			yield return new Team("FC Nordsjlland", FcNordsjlland);
			yield return new Team("FC Porto", FcPorto);
			yield return new Team("FC Rostov", FcRostov);
			yield return new Team("FC Schalke 04", FcSchalke04);
			yield return new Team("FC Seoul", FcSeoul);
			yield return new Team("FC Sion", FcSion);
			yield return new Team("FC Sochaux", FcSochaux);
			yield return new Team("FC St. Gallen", FcStGallen);
			yield return new Team("FC St. Pauli", FcStPauli);
			yield return new Team("FC Thun", FcThun);
			yield return new Team("FC Twente", FcTwente);
			yield return new Team("FC Utrecht", FcUtrecht);
			yield return new Team("FC Volga Nizhniy Novgorod", FcVolgaNizhniyNovgorod);
			yield return new Team("FC Zurich", FcZurich);
			yield return new Team("Feyenoord", Feyenoord);
			yield return new Team("Figueirense", Figueirense);
			yield return new Team("Fiorentina", Fiorentina);
			yield return new Team("FK Haugesund", FkHaugesund);
			yield return new Team("Flamengo", Flamengo);
			yield return new Team("Fleetwood Town", FleetwoodTown);
			yield return new Team("Fluminense", Fluminense);
			yield return new Team("Fortuna Dsseldorf", FortunaDsseldorf);
			yield return new Team("Fredrikstad FK", FredrikstadFk);
			yield return new Team("FSV Frankfurt", FsvFrankfurt);
			yield return new Team("Fulham", Fulham);
			yield return new Team("GAIS", Gais);
			yield return new Team("Galatasaray SK", GalatasaraySk);
			yield return new Team("Galway United", GalwayUnited);
			yield return new Team("Gangwon FC", GangwonFc);
			yield return new Team("Gazelec Ajaccio", GazelecAjaccio);
			yield return new Team("Gefle IF", GefleIf);
			yield return new Team("Genk", Genk);
			yield return new Team("Genoa", Genoa);
			yield return new Team("Gent", Gent);
			yield return new Team("Getafe CF", GetafeCf);
			yield return new Team("GIF Sundsvall", GifSundsvall);
			yield return new Team("Gil Vicente ", GilVicente);
			yield return new Team("Gil Vicente FC", GilVicenteFc);
			yield return new Team("Gillingham", Gillingham);
			yield return new Team("Girona FC", GironaFc);
			yield return new Team("Girondins Bordeaux", GirondinsBordeaux);
			yield return new Team("GKS Belchatow", GksBelchatow);
			yield return new Team("Gliwice", Gliwice);
			yield return new Team("Gold Coast United", GoldCoastUnited);
			yield return new Team("Gornik Zabrze", GornikZabrze);
			yield return new Team("Granada CF", GranadaCf);
			yield return new Team("Grasshopper-Club", GrasshopperClub);
			yield return new Team("Gremio", Gremio);
			yield return new Team("Grosseto", Grosseto);
			yield return new Team("Guadalajara", Guadalajara);
			yield return new Team("Guimaraes", Guimaraes);
			yield return new Team("GwangJu FC", GwangJuFc);
			yield return new Team("GyeongNam FC", GyeongNamFc);
			yield return new Team("Hajer", Hajer);
			yield return new Team("Halmstads BK", HalmstadsBk);
			yield return new Team("Hamburger SV", HamburgerSv);
			yield return new Team("Hannover 96", Hannover96);
			yield return new Team("Hansa Rostock", HansaRostock);
			yield return new Team("Hartlepool United", HartlepoolUnited);
			yield return new Team("Heart of Midlothian", HeartofMidlothian);
			yield return new Team("Helsingborgs IF", HelsingborgsIf);
			yield return new Team("Heracles Almelo", HeraclesAlmelo);
			yield return new Team("Hercules CF", HerculesCf);
			yield return new Team("Hereford United", HerefordUnited);
			yield return new Team("Hertha BSC", HerthaBsc);
			yield return new Team("Hibernian", Hibernian);
			yield return new Team("Honefoss BK", HonefossBk);
			yield return new Team("Houston Dynamo", HoustonDynamo);
			yield return new Team("Huddersfield Town", HuddersfieldTown);
			yield return new Team("Hull City", HullCity);
			yield return new Team("IF Elfsborg", IfElfsborg);
			yield return new Team("IFK Goteborg", IfkGoteborg);
			yield return new Team("IFK Norrkoping", IfkNorrkoping);
			yield return new Team("IK Start", IkStart);
			yield return new Team("Incheon United FC", IncheonUnitedFc);
			yield return new Team("Inter", Inter);
			yield return new Team("Internacional", Internacional);
			yield return new Team("Inverness Caledonian Thistle", InvernessCaledonianThistle);
			yield return new Team("Ipswich Town", IpswichTown);
			yield return new Team("Jagiellonia Bialystok", JagielloniaBialystok);
			yield return new Team("Jaguares de Chiapas", JaguaresdeChiapas);
			yield return new Team("Jeju United FC", JejuUnitedFc);
			yield return new Team("Jeonbuk Hyundai Motors", JeonbukHyundaiMotors);
			yield return new Team("Juve Stabia", JuveStabia);
			yield return new Team("Juventus", Juventus);
			yield return new Team("Kaizer Chiefs", KaizerChiefs);
			yield return new Team("Kalmar FF", KalmarFf);
			yield return new Team("Kapfenberger SV", KapfenbergerSv);
			yield return new Team("Karlsruher SC", KarlsruherSc);
			yield return new Team("Kilmarnock", Kilmarnock);
			yield return new Team("Korona Kielce", KoronaKielce);
			yield return new Team("Kortrijk", Kortrijk);
			yield return new Team("Krylya Sovetov Samara", KrylyaSovetovSamara);
			yield return new Team("Kuban Krasnodar", KubanKrasnodar);
			yield return new Team("La Spezia", LaSpezia);
			yield return new Team("Lanciano", Lanciano);
			yield return new Team("Lazio", Lazio);
			yield return new Team("LB Chateauroux", LbChateauroux);
			yield return new Team("Le Havre AC", LeHavreAc);
			yield return new Team("Le Mans FC", LeMansFc);
			yield return new Team("Lecce", Lecce);
			yield return new Team("Lech Poznan", LechPoznan);
			yield return new Team("Lechia Gdansk", LechiaGdansk);
			yield return new Team("Leeds United", LeedsUnited);
			yield return new Team("Legia Warszawa", LegiaWarszawa);
			yield return new Team("Leicester City", LeicesterCity);
			yield return new Team("Levante UD", LevanteUd);
			yield return new Team("Leyton Orient", LeytonOrient);
			yield return new Team("Lierse", Lierse);
			yield return new Team("Lillestrom SK", LillestromSk);
			yield return new Team("Liverpool", Liverpool);
			yield return new Team("Livorno", Livorno);
			yield return new Team("LKS Lodz", LksLodz);
			yield return new Team("Lokeren", Lokeren);
			yield return new Team("Lokomotiv Moskva", LokomotivMoskva);
			yield return new Team("Los Angeles Galaxy", LosAngelesGalaxy);
			yield return new Team("LOSC Lille", LoscLille);
			yield return new Team("Macclesfield Town", MacclesfieldTown);
			yield return new Team("Malaga CF", MalagaCf);
			yield return new Team("Malmo FF", MalmoFf);
			yield return new Team("Manchester City", ManchesterCity);
			yield return new Team("Manchester United", ManchesterUnited);
			yield return new Team("Maritimo", Maritimo);
			yield return new Team("Mechelen", Mechelen);
			yield return new Team("Melbourne Heart", MelbourneHeart);
			yield return new Team("Melbourne Victory", MelbourneVictory);
			yield return new Team("Middlesbrough", Middlesbrough);
			yield return new Team("Milan", Milan);
			yield return new Team("Millwall", Millwall);
			yield return new Team("Milton Keynes Dons", MiltonKeynesDons);
			yield return new Team("Mjallby AIF", MjallbyAif);
			yield return new Team("Modena", Modena);
			yield return new Team("Molde FK", MoldeFk);
			yield return new Team("Monarcas Morelia", MonarcasMorelia);
			yield return new Team("Monterrey", Monterrey);
			yield return new Team("Montpellier SC", MontpellierSc);
			yield return new Team("Montreal Impact", MontrealImpact);
			yield return new Team("Mordov. Saransk", MordovSaransk);
			yield return new Team("Morecambe", Morecambe);
			yield return new Team("Moreira Conegos", MoreiraConegos);
			yield return new Team("Moreirense", Moreirense);
			yield return new Team("Motherwell", Motherwell);
			yield return new Team("MSV Duisburg", MsvDuisburg);
			yield return new Team("N. Recife", NRecife);
			yield return new Team("NAC Breda", NacBreda);
			yield return new Team("Najran", Najran);
			yield return new Team("Napoli", Napoli);
			yield return new Team("Nastic de Tarragona", NasticdeTarragona);
			yield return new Team("NEC", Nec);
			yield return new Team("Neuchatel Xamax", NeuchatelXamax);
			yield return new Team("New England Revolution", NewEnglandRevolution);
			yield return new Team("New York Red Bulls", NewYorkRedBulls);
			yield return new Team("Newcastle United", NewcastleUnited);
			yield return new Team("Newcastle United Jets", NewcastleUnitedJets);
			yield return new Team("Nimes Olympique", NimesOlympique);
			yield return new Team("Northampton Town", NorthamptonTown);
			yield return new Team("Norwich City", NorwichCity);
			yield return new Team("Nottingham Forest", NottinghamForest);
			yield return new Team("Notts County", NottsCounty);
			yield return new Team("Novara", Novara);
			yield return new Team("Odd Grenland", OddGrenland);
			yield return new Team("Odense BK ", OdenseBk);
			yield return new Team("OGC Nice", OgcNice);
			yield return new Team("Oldham Athletic", OldhamAthletic);
			yield return new Team("Olhanense ", Olhanense);
			yield return new Team("Olympiakos", Olympiakos);
			yield return new Team("Olympique de Marseille", OlympiquedeMarseille);
			yield return new Team("Olympique Lyonnais", OlympiqueLyonnais);
			yield return new Team("Orebro SK", OrebroSk);
			yield return new Team("Orlando Pirates", OrlandoPirates);
			yield return new Team("Oud-Heverlee Leuven", OudHeverleeLeuven);
			yield return new Team("Oxford United", OxfordUnited);
			yield return new Team("P. Campinas", PCampinas);
			yield return new Team("Pachuca", Pachuca);
			yield return new Team("Pacos de Ferreira", PacosdeFerreira);
			yield return new Team("Padova", Padova);
			yield return new Team("Palermo", Palermo);
			yield return new Team("Palmeiras", Palmeiras);
			yield return new Team("Panathinaikos", Panathinaikos);
			yield return new Team("PAOK", Paok);
			yield return new Team("Paris Saint-Germain", ParisSaintGermain);
			yield return new Team("Parma", Parma);
			yield return new Team("PEC Zwolle", PecZwolle);
			yield return new Team("Perth Glory", PerthGlory);
			yield return new Team("Pescara", Pescara);
			yield return new Team("Peterborough United", PeterboroughUnited);
			yield return new Team("Philadelphia Union", PhiladelphiaUnion);
			yield return new Team("Plymouth Argyle", PlymouthArgyle);
			yield return new Team("Podbeskidzie Bielsko-Biala", PodbeskidzieBielskoBiala);
			yield return new Team("Pohang Steelers", PohangSteelers);
			yield return new Team("Polonia Warszawa", PoloniaWarszawa);
			yield return new Team("Port Vale", PortVale);
			yield return new Team("Portland Timbers", PortlandTimbers);
			yield return new Team("Portsmouth", Portsmouth);
			yield return new Team("Portuguesa", Portuguesa);
			yield return new Team("Preston North End", PrestonNorthEnd);
			yield return new Team("PSV", Psv);
			yield return new Team("Puebla", Puebla);
			yield return new Team("Queens Park Rangers", QueensParkRangers);
			yield return new Team("Queretaro", Queretaro);
			yield return new Team("Racing Club de Lens", RacingClubdeLens);
			yield return new Team("Racing de Santander", RacingdeSantander);
			yield return new Team("Randers FC", RandersFc);
			yield return new Team("Rapid Wien", RapidWien);
			yield return new Team("Rayo Vallecano", RayoVallecano);
			yield return new Team("RC Celta de Vigo", RcCeltadeVigo);
			yield return new Team("RC Deportivo", RcDeportivo);
			yield return new Team("RC Recreativo", RcRecreativo);
			yield return new Team("RCD Espanyol", RcdEspanyol);
			yield return new Team("RCD Mallorca", RcdMallorca);
			yield return new Team("Reading", Reading);
			yield return new Team("Real Betis Balompie", RealBetisBalompie);
			yield return new Team("Real Madrid", RealMadrid);
			yield return new Team("Real Murcia CF", RealMurciaCf);
			yield return new Team("Real Salt Lake", RealSaltLake);
			yield return new Team("Real Sociedad", RealSociedad);
			yield return new Team("Real Sporting de Gijon", RealSportingdeGijon);
			yield return new Team("Real Valladolid", RealValladolid);
			yield return new Team("Real Zaragoza", RealZaragoza);
			yield return new Team("Red Bull Salzburg", RedBullSalzburg);
			yield return new Team("Reggina", Reggina);
			yield return new Team("Rio Ave ", RioAve);
			yield return new Team("Rio Ave FC", RioAveFc);
			yield return new Team("RKC Waalwijk", RkcWaalwijk);
			yield return new Team("RM Castilla", RmCastilla);
			yield return new Team("Rochdale", Rochdale);
			yield return new Team("Roda JC Kerkrade", RodaJcKerkrade);
			yield return new Team("Roma", Roma);
			yield return new Team("Rosenborg BK", RosenborgBk);
			yield return new Team("Ross County", RossCounty);
			yield return new Team("Rotherham United", RotherhamUnited);
			yield return new Team("Rubin Kazan", RubinKazan);
			yield return new Team("Ruch Chorzow", RuchChorzow);
			yield return new Team("S. Recife", SRecife);
			yield return new Team("Sampdoria", Sampdoria);
			yield return new Team("San Jose Earthquakes", SanJoseEarthquakes);
			yield return new Team("San Luis", SanLuis);
			yield return new Team("Sandnes Ulf", SandnesUlf);
			yield return new Team("Sangju Sangmu Phoenix FC", SangjuSangmuPhoenixFc);
			yield return new Team("Santos", Santos);
			yield return new Team("Santos Laguna", SantosLaguna);
			yield return new Team("Sao Paulo", SaoPaulo);
			yield return new Team("Sassuolo", Sassuolo);
			yield return new Team("SC Bastia", ScBastia);
			yield return new Team("SC Beira-Mar", ScBeiraMar);
			yield return new Team("SC Braga", ScBraga);
			yield return new Team("SC Freiburg", ScFreiburg);
			yield return new Team("SC Heerenveen", ScHeerenveen);
			yield return new Team("SC Olhanense", ScOlhanense);
			yield return new Team("SC Paderborn", ScPaderborn);
			yield return new Team("SC Wiener Neustadt", ScWienerNeustadt);
			yield return new Team("Scunthorpe United", ScunthorpeUnited);
			yield return new Team("SD Huesca", SdHuesca);
			yield return new Team("SD Ponferradina", SdPonferradina);
			yield return new Team("Seattle Sounders", SeattleSounders);
			yield return new Team("Seongnam Ilhwa Chunma", SeongnamIlhwaChunma);
			yield return new Team("Servette FC", ServetteFc);
			yield return new Team("Sevilla FC", SevillaFc);
			yield return new Team("Shamrock Rovers", ShamrockRovers);
			yield return new Team("Sheffield United", SheffieldUnited);
			yield return new Team("Sheffield Wednesday", SheffieldWednesday);
			yield return new Team("Shelbourne", Shelbourne);
			yield return new Team("Shrewsbury Town", ShrewsburyTown);
			yield return new Team("Siena", Siena);
			yield return new Team("Silkeborg IF", SilkeborgIf);
			yield return new Team("SK Brann", SkBrann);
			yield return new Team("SL Benfica", SlBenfica);
			yield return new Team("Slask Wroclaw", SlaskWroclaw);
			yield return new Team("Sligo Rovers", SligoRovers);
			yield return new Team("SM Caen", SmCaen);
			yield return new Team("Snderjyske ", Snderjyske);
			yield return new Team("Sogndal Fotball", SogndalFotball);
			yield return new Team("Southampton", Southampton);
			yield return new Team("Southend United", SouthendUnited);
			yield return new Team("Spartak Moskva", SpartakMoskva);
			yield return new Team("Spartak Nalchik", SpartakNalchik);
			yield return new Team("Sporting CP", SportingCp);
			yield return new Team("Sporting KC", SportingKc);
			yield return new Team("Sporting Lisbon", SportingLisbon);
			yield return new Team("SPVGG Greuther Frth", SpvggGreutherFrth);
			yield return new Team("SSV Jahn", SsvJahn);
			yield return new Team("St. Johnstone", StJohnstone);
			yield return new Team("St. Mirren", StMirren);
			yield return new Team("St. Patrick's Athletic", StPatricksAthletic);
			yield return new Team("Stabaek Fotball", StabaekFotball);
			yield return new Team("Stade Brestois", StadeBrestois);
			yield return new Team("Stade de Reims", StadedeReims);
			yield return new Team("Stade Lavallois", StadeLavallois);
			yield return new Team("Stade Rennais", StadeRennais);
			yield return new Team("Standard", Standard);
			yield return new Team("Stevenage", Stevenage);
			yield return new Team("Stoke City", StokeCity);
			yield return new Team("Stromsgodset Toppfotball", StromsgodsetToppfotball);
			yield return new Team("Sturm Graz", SturmGraz);
			yield return new Team("Sunderland", Sunderland);
			yield return new Team("Suwon Samsung Bluewings", SuwonSamsungBluewings);
			yield return new Team("SV Mattersburg", SvMattersburg);
			yield return new Team("SV Ried", SvRied);
			yield return new Team("SV Sandhausen", SvSandhausen);
			yield return new Team("Swansea City", SwanseaCity);
			yield return new Team("Swindon Town", SwindonTown);
			yield return new Team("Sydney FC", SydneyFc);
			yield return new Team("Syrianska FC", SyrianskaFc);
			yield return new Team("Szczecin", Szczecin);
			yield return new Team("Terek Grozny", TerekGrozny);
			yield return new Team("Terni", Terni);
			yield return new Team("Tigres U.A.N.L.", TigresUanl);
			yield return new Team("Toluca", Toluca);
			yield return new Team("Tom Tomsk", TomTomsk);
			yield return new Team("Torino", Torino);
			yield return new Team("Toronto FC", TorontoFc);
			yield return new Team("Torquay United", TorquayUnited);
			yield return new Team("Tottenham Hotspur", TottenhamHotspur);
			yield return new Team("Toulouse FC", ToulouseFc);
			yield return new Team("Tours FC", ToursFc);
			yield return new Team("Tranmere Rovers", TranmereRovers);
			yield return new Team("Tromso IL", TromsoIl);
			yield return new Team("TSV 1860 Munchen", Tsv1860Munchen);
			yield return new Team("U.C.D.", Ucd);
			yield return new Team("U.N.A.M.", Unam);
			yield return new Team("UD Almeria", UdAlmeria);
			yield return new Team("UD Las Palmas", UdLasPalmas);
			yield return new Team("Udinese", Udinese);
			yield return new Team("Ulsan Hyundai FC", UlsanHyundaiFc);
			yield return new Team("Uniao Desportiva de Leiria", UniaoDesportivadeLeiria);
			yield return new Team("US Boulogne", UsBoulogne);
			yield return new Team("Valencia CF", ValenciaCf);
			yield return new Team("Valenciennes FC", ValenciennesFc);
			yield return new Team("Valerenga Fotball", ValerengaFotball);
			yield return new Team("Vancouver Whitecaps", VancouverWhitecaps);
			yield return new Team("Varese", Varese);
			yield return new Team("Vasco da Gama", VascodaGama);
			yield return new Team("Vercelli", Vercelli);
			yield return new Team("Verona", Verona);
			yield return new Team("VfB Stuttgart", VfBStuttgart);
			yield return new Team("VfL Bochum", VfLBochum);
			yield return new Team("VfL Wolfsburg", VfLWolfsburg);
			yield return new Team("VfR Aalen", VfRAalen);
			yield return new Team("Vicenza", Vicenza);
			yield return new Team("Viking FK", VikingFk);
			yield return new Team("Villarreal B", VillarrealB);
			yield return new Team("Villarreal CF", VillarrealCf);
			yield return new Team("Vitesse", Vitesse);
			yield return new Team("Vitoria Guimaraes", VitoriaGuimaraes);
			yield return new Team("Vitoria Setubal", VitoriaSetubal);
			yield return new Team("VVV-Venlo", VvvVenlo);
			yield return new Team("Waasland-Beveren", WaaslandBeveren);
			yield return new Team("Wacker Innsbruck", WackerInnsbruck);
			yield return new Team("Walsall", Walsall);
			yield return new Team("Wanderers FC", WanderersFc);
			yield return new Team("Waregem", Waregem);
			yield return new Team("Watford", Watford);
			yield return new Team("Wellington Phoenix", WellingtonPhoenix);
			yield return new Team("Werder Bremen", WerderBremen);
			yield return new Team("West Bromwich Albion", WestBromwichAlbion);
			yield return new Team("West Ham United", WestHamUnited);
			yield return new Team("Widzew Lodz", WidzewLodz);
			yield return new Team("Wigan Athletic", WiganAthletic);
			yield return new Team("Willem II", WillemIi);
			yield return new Team("Wisla Krakow", WislaKrakow);
			yield return new Team("Wolfsberger AC", WolfsbergerAc);
			yield return new Team("Wolverhampton Wanderers", WolverhamptonWanderers);
			yield return new Team("Wycombe Wanderers", WycombeWanderers);
			yield return new Team("Xerez CD", XerezCd);
			yield return new Team("Xoloitzcuintles de Tijuana", XoloitzcuintlesdeTijuana);
			yield return new Team("Yeovil Town", YeovilTown);
			yield return new Team("York City", YorkCity);
			yield return new Team("Zaglebie Lubin", ZaglebieLubin);
			yield return new Team("Zenit St. Petersburg", ZenitStPetersburg);
		}
	}
}
